// <auto-generated />
using System;
using Ecommerce.Estoque.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ecommerce.Estoque.Migrations
{
    [DbContext(typeof(EstoqueDbContext))]
    partial class EstoqueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Shared.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_Products_Category");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Products_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Products_Name");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("IX_Products_Sku");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Category = "Eletrônicos",
                            CreatedAt = new DateTime(2025, 10, 30, 0, 9, 29, 19, DateTimeKind.Utc).AddTicks(4873),
                            Description = "Smartphone top de linha com 256GB de armazenamento",
                            IsActive = true,
                            Name = "Smartphone Samsung Galaxy S23",
                            Price = 2499.99m,
                            Sku = "SAMS23-256",
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Category = "Informática",
                            CreatedAt = new DateTime(2025, 10, 30, 0, 9, 29, 19, DateTimeKind.Utc).AddTicks(5037),
                            Description = "Notebook profissional com Intel i7 e 16GB RAM",
                            IsActive = true,
                            Name = "Notebook Lenovo ThinkPad",
                            Price = 4299.99m,
                            Sku = "LEN-TP-I7",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Category = "Áudio",
                            CreatedAt = new DateTime(2025, 10, 30, 0, 9, 29, 19, DateTimeKind.Utc).AddTicks(5040),
                            Description = "Fone com cancelamento de ruído ativo",
                            IsActive = true,
                            Name = "Fone de Ouvido Sony WH-1000XM5",
                            Price = 1599.99m,
                            Sku = "SONY-WH1000",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Category = "TV e Home Theater",
                            CreatedAt = new DateTime(2025, 10, 30, 0, 9, 29, 19, DateTimeKind.Utc).AddTicks(5043),
                            Description = "Smart TV com resolução 4K e HDR",
                            IsActive = true,
                            Name = "Smart TV 55\" 4K Samsung",
                            Price = 3299.99m,
                            Sku = "SAMS-TV55-4K",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Category = "Games",
                            CreatedAt = new DateTime(2025, 10, 30, 0, 9, 29, 19, DateTimeKind.Utc).AddTicks(5045),
                            Description = "Console de videogame de última geração",
                            IsActive = true,
                            Name = "Console PlayStation 5",
                            Price = 4499.99m,
                            Sku = "SONY-PS5",
                            StockQuantity = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
